/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedScenariosRouteImport } from './routes/_authenticated.scenarios'
import { Route as AuthenticatedReviewerRouteImport } from './routes/_authenticated.reviewer'
import { Route as AuthenticatedSessionsSessionIdRouteImport } from './routes/_authenticated.sessions.$sessionId'
import { Route as AuthenticatedSessionsSessionIdReportRouteImport } from './routes/_authenticated.sessions.$sessionId.report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScenariosRoute = AuthenticatedScenariosRouteImport.update({
  id: '/_authenticated/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReviewerRoute = AuthenticatedReviewerRouteImport.update({
  id: '/_authenticated/reviewer',
  path: '/reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSessionsSessionIdRoute =
  AuthenticatedSessionsSessionIdRouteImport.update({
    id: '/_authenticated/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSessionsSessionIdReportRoute =
  AuthenticatedSessionsSessionIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedSessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reviewer': typeof AuthenticatedReviewerRoute
  '/scenarios': typeof AuthenticatedScenariosRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRouteWithChildren
  '/sessions/$sessionId/report': typeof AuthenticatedSessionsSessionIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reviewer': typeof AuthenticatedReviewerRoute
  '/scenarios': typeof AuthenticatedScenariosRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRouteWithChildren
  '/sessions/$sessionId/report': typeof AuthenticatedSessionsSessionIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/reviewer': typeof AuthenticatedReviewerRoute
  '/_authenticated/scenarios': typeof AuthenticatedScenariosRoute
  '/_authenticated/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRouteWithChildren
  '/_authenticated/sessions/$sessionId/report': typeof AuthenticatedSessionsSessionIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reviewer'
    | '/scenarios'
    | '/sessions/$sessionId'
    | '/sessions/$sessionId/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reviewer'
    | '/scenarios'
    | '/sessions/$sessionId'
    | '/sessions/$sessionId/report'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/reviewer'
    | '/_authenticated/scenarios'
    | '/_authenticated/sessions/$sessionId'
    | '/_authenticated/sessions/$sessionId/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedReviewerRoute: typeof AuthenticatedReviewerRoute
  AuthenticatedScenariosRoute: typeof AuthenticatedScenariosRoute
  AuthenticatedSessionsSessionIdRoute: typeof AuthenticatedSessionsSessionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scenarios': {
      id: '/_authenticated/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof AuthenticatedScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reviewer': {
      id: '/_authenticated/reviewer'
      path: '/reviewer'
      fullPath: '/reviewer'
      preLoaderRoute: typeof AuthenticatedReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sessions/$sessionId': {
      id: '/_authenticated/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sessions/$sessionId/report': {
      id: '/_authenticated/sessions/$sessionId/report'
      path: '/report'
      fullPath: '/sessions/$sessionId/report'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdReportRouteImport
      parentRoute: typeof AuthenticatedSessionsSessionIdRoute
    }
  }
}

interface AuthenticatedSessionsSessionIdRouteChildren {
  AuthenticatedSessionsSessionIdReportRoute: typeof AuthenticatedSessionsSessionIdReportRoute
}

const AuthenticatedSessionsSessionIdRouteChildren: AuthenticatedSessionsSessionIdRouteChildren =
  {
    AuthenticatedSessionsSessionIdReportRoute:
      AuthenticatedSessionsSessionIdReportRoute,
  }

const AuthenticatedSessionsSessionIdRouteWithChildren =
  AuthenticatedSessionsSessionIdRoute._addFileChildren(
    AuthenticatedSessionsSessionIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedReviewerRoute: AuthenticatedReviewerRoute,
  AuthenticatedScenariosRoute: AuthenticatedScenariosRoute,
  AuthenticatedSessionsSessionIdRoute:
    AuthenticatedSessionsSessionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
